### ISSUE TITLE
Methods for obtaining the distantly supervised data

### ISSUE THREAD

**Issue by tonytan48** [qiaojiim/HacRED#1]
Hi, thank you for your work on HacRED dataset. May I know is it possible for you to release the source code for obtaining the distantly supervised data? We are interested in producing similar data for south east asian languages.

**Comment by qiaojiim** [comment]
Hi, thank you for your attention to our work. 
For the sake of versatility and usability, we will re-organize our codes and make them public soon. 
Obviously, some customized features like Chinese NLP toolkits have been integrated into the construction of HacRED.

**Comment by tonytan48** [comment]
Thank you for your prompt reply.
