### ISSUE TITLE
Baseline implementations

### ISSUE THREAD

**Issue by tonytan48** [qiaojiim/HacRED#2]
Hi, thank you for your nice work. I am wondering can you provide baseline implementation or description for end2end and in relation classification? For example, the ATLOP for RC is 77.51 F1 but I did not find the description in the paper, like using xlm-r or chinese bert/ word or char level.

**Comment by qiaojiim** [comment]
I wonder if you are paying attention to the document-level relational classification model like GAIN, ATLOP, not the same as the end-to-end you mentioned.
For all 4 doc.-level RC models, we employ PLMs at the chinese char-level.
For ATLOP, we use chinese-roberta-wwm-ext-large.

**Comment by qiaojiim** [comment]
We directly adapt the source code provided by the authors to conduct experiments on the HacRED, since the format is similar to the DocRED.

**Comment by tonytan48** [comment]
Thank you for your prompt reply, I am clear on the encoder part now. I understand that the relation classification experiments are implemented by GAIN/ATLOP etc. 
But as far as I know, PURE is a pipeline end-to-end RE model for sentence-level RE task. I ran their code before and I am wondering how did you use that for Document-level end-to-end relation extraction task. Firstly, the relation classification part for PURE model is by creating multiple instances if there are more than 2 entities for one sentence.  If there are 10 entities for one document, does your experiment replicate this document into 10*9 instances? I mainly want to ask how does the PURE implementation for end-to-end relation extraction task work.

**Comment by qiaojiim** [comment]
You are right. 
Function `generate_relation_data` in the source code will prepare the instances for PURE RC model, where 10 ner will result in 10*9 entity pairs (e1!=e2)
