### ISSUE TITLE
关于测试集评测

### ISSUE THREAD

**Issue by chenshaowei57** [qiaojiim/HacRED#3]
作者您好，您提供的测试集中没有包含labels_char和labels_word的标准答案。
所以想问一下如果想在您提供的数据集上进行实验的话，应该如何对测试集进行评测呀？是有在线评测的入口么？

**Comment by qiaojiim** [comment]
我们更新了google drive的test.json文件，包含标注信息哈

**Comment by chenshaowei57** [comment]
感谢您的回复！已经下载到最新的测试集。
此外，还有一个问题想咨询一下：您在论文中分析了不同hard case下的模型性能，不知是否方便公开一下不同hard case下的评测子集，或者筛选hard case的代码？

**Comment by qiaojiim** [comment]
相关的test子集已经更新到google drive的hard cases for detailed analysis文件夹下

**Comment by chenshaowei57** [comment]
收到，十分感谢！
