### ISSUE TITLE
Evaluation metrcis of Baseline

### ISSUE THREAD

**Issue by Buted** [qiaojiim/HacRED#4]
Hi, thanks for your interesting work. I see some baseline in your paper (Table 8). I am wondering what the evaluation metric you are reporting for end-to-end RE models. `Boundary evaluation` or `Strict evaluation`?

**Comment by qiaojiim** [comment]
In Chinese, we use the char-level PLMs and generally an entity mention consists of multiple tokens.
So we use the strict evaluation (exact match) which means an entity is regarded as correct only if its span boundary is correct.
